version: '3.5'

services:
  laravel-app:
    image: apache-php:3.0
    build:
      context: ./docker/
      dockerfile: Dockerfile-Apache-Php
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./back:/var/www/html
      - .env:/var/www/html/.env
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mysql:5.7.40
    container_name: mysql-db
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ludorootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network