FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g @angular/cli@20

EXPOSE 5000 49153

CMD rm -rf node_modules package-lock.json && npm cache clean --force && npm install --legacy-peer-deps && ng serve --hmr --poll 500 --port 5000 --host 0.0.0.0 --disable-host-check