name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copie fichier de déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./build/
        server-dir: /www/ludoscore_deploiement
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
