name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Front Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: ./front
      
    - name: Build Front
      run: npm run build -- --configuration production
      working-directory: ./front
      
    - name: Déploiement Front
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.cluster028.hosting.ovh.net
        local-dir: ./front/dist/app/
        server-dir: /www/ludoscore/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
    
    - name: Installation des dépendances
      uses: php-actions/composer@v6
      with:
        command: install --no-dev --ansi --no-progress --no-interaction --prefer-dist --working-dir=./back/
    
    - name: Compression du repertoire
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ./deployment/back.zip ./back
    
    - name: Création du fichier .env
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "./deployment/.env"
        FILE_DATA: "SESSION_DRIVER=cookie\rSESSION_DOMAIN=.lgda.fr\rSANCTUM_STATEFUL_DOMAINS=*.lgda.fr:443,lgda.fr,www.lgda.fr\rAPP_NAME=\"LudoScore Back\"\rAPP_ENV=local\rAPP_KEY=${{ secrets.APP_KEY }}\rAPP_DEBUG=true\rAPP_URL=https://www.lgda.fr/ludoscoreback\rLOG_CHANNEL=stack\rLOG_DEPRECATIONS_CHANNEL=null\rLOG_LEVEL=debug\rDB_HOST=lgdafrglegenie.mysql.db\rDB_PORT=3306\rDB_DATABASE=lgdafrglegenie\rDB_USERNAME=${{ secrets.BDD_USERNAME }}\rDB_PASSWORD=${{ secrets.BDD_PASSWORD }}\rDB_PREFIX=ludo$\r"
      
    - name: Copie des fichiers pour le déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./deployment/
        server-dir: /www/ludoscore_deploiement/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
        
    - name: Suppression de la version précédente
      uses: satak/webrequest-action@master
      with:
        url: https://www.lgda.fr/ludoscore_deploiement/clean.php
        method: GET
    
    - name: Lancement du déploiement distant
      uses: satak/webrequest-action@master
      with:
        url: https://www.lgda.fr/ludoscore_deploiement/install.php
        method: GET
        
    - name: Lancement de la migration si besoin
      uses: satak/webrequest-action@master
      with:
        url: https://www.lgda.fr/ludoscoreback/finir_installation
        method: GET
      