name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        command: install --working-dir=./back/
    
    - name: Création du fichier .env
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "./deployment/.env"
        FILE_DATA: "APP_NAME=\"LudoScore Back\"\rAPP_ENV=local\rAPP_KEY=${{ secrets.APP_KEY }}\rAPP_DEBUG=true\rAPP_URL=https://www.lgda.fr/ludoscore\rLOG_CHANNEL=stack\rLOG_DEPRECATIONS_CHANNEL=null\rLOG_LEVEL=debug\rDB_HOST=lgdafrglegenie.mysql.db\rDB_PORT=3306\rDB_DATABASE=lgdafrglegenie\rDB_USERNAME=${{ secrets.BDD_USERNAME }}\rDB_PASSWORD=${{ secrets.BDD_PASSWORD }}\rDB_PREFIX=ludo$\r"
        
    - name: Copie des fichiers pour le déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./deployment/
        server-dir: /www/ludoscore_deploiement/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
