name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Création du fichier .env
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "./deployment/.env"
        FILE_DATA: "APP_NAME=`\"LudoScore Back\"\r\nAPP_ENV=local\r\nAPP_KEY=${{ secrets.APP_KEY }}\r\nAPP_DEBUG=true\r\nAPP_URL=https://www.lgda.fr/ludoscore\r\nLOG_CHANNEL=stack\r\nLOG_DEPRECATIONS_CHANNEL=null\r\nLOG_LEVEL=debug\r\nDB_HOST=lgdafrglegenie.mysql.db\r\nDB_PORT=3306\r\nDB_DATABASE=lgdafrglegenie\r\nDB_USERNAME=${{ secrets.BDD_USERNAME }}\r\nDB_PASSWORD=${{ secrets.BDD_PASSWORD }}\r\nDB_PREFIX=ludo$\r\n"
        
    - name: Copie des fichiers pour le déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./deployment/
        server-dir: /www/ludoscore_deploiement/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
