name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Copie fichier de déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./deployment/
        server-dir: /www/ludoscore_deploiement/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
        
    - name: Création du .env
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://www.lgda.fr/ludoscore_deploiement/environnement.php'
        method: 'POST'
        data: '{"APP_NAME": "LudoScore Back", "APP_ENV": "local", "APP_KEY": "${{ secrets.APP_KEY }}", "APP_DEBUG": "true", "APP_URL": "https://www.lgda.fr/ludoscore", "LOG_CHANNEL": "stack", "LOG_DEPRECATIONS_CHANNEL": "null", "LOG_LEVEL": "debug", "DB_HOST": "lgdafrglegenie.mysql.db", "DB_PORT": "3306", "DB_DATABASE": "lgdafrglegenie", "DB_USERNAME": "${{ secrets.BDD_USERNAME }}", "DB_PASSWORD": "${{ secrets.BDD_PASSWORD }}", "DB_PREFIX": "ludo$"}'
