name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Copie fichier de déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./deployment/
        server-dir: /www/ludoscore_deploiement/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
        
    - name: Création du .env
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://www.lgda.fr/ludoscore_deploiement'
        method: 'POST'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
