name: Construction & Deploiement du site sur OVH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Front Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: ./front
      
    - name: Build Front
      run: npm run build -- --configuration production
      working-directory: ./front
      
    - name: Déploiement Front
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.cluster028.hosting.ovh.net
        local-dir: ./front/dist/app/
        server-dir: /www/ludoscore/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
    
    - name: Installation des dépendances
      uses: php-actions/composer@v6
      with:
        command: install --no-dev --ansi --no-progress --no-interaction --prefer-dist --working-dir=./back/
    
    - name: Compression du repertoire
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ./deployment/back.zip ./back
    
    - name: Remplacement des variables d'environnement
      run: |-
        sed -i "s/VARIABLE_IMAGES_PATH/${{vars.IMAGES_PATH}}/g" "./deployment/.env"
        sed -i "s/SECRET_APP_KEY/${{secrets.APP_KEY}}/g" "./deployment/.env"
        sed -i "s/SECRET_BDD_USERNAME/${{secrets.BDD_USERNAME}}/g" "./deployment/.env"
        sed -i "s/SECRET_BDD_PASSWORD/${{secrets.BDD_PASSWORD}}/g" "./deployment/.env"
        sed -i "s/VARIABLE_BDD_PREFIX/${{vars.BDD_PREFIX}}/g" "./deployment/.env"
        sed -i "s/SECRET_PUSHER_APP_ID/${{secrets.PUSHER_APP_ID}}/g" "./deployment/.env"
        sed -i "s/SECRET_PUSHER_APP_KEY/${{secrets.PUSHER_APP_KEY}}/g" "./deployment/.env"
        sed -i "s/SECRET_PUSHER_APP_SECRET/${{secrets.PUSHER_APP_SECRET}}/g" "./deployment/.env"
        sed -i "s/VARIABLE_BACK_URL/${{vars.BACK_URL}}/g" "./deployment/.env"
        sed -i "s/VARIABLE_NAME/${{vars.NAME}}/g" "./deployment/.env"
        
      
    - name: Copie des fichiers pour le déploiement
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.OVH_SERVER }}
        local-dir: ./deployment/
        server-dir: /www/ludoscore_deploiement/
        dangerous-clean-slate: true
        username: ${{ secrets.OVH_USERNAME }}
        password: ${{ secrets.OVH_PASSWORD }}
        
    - name: Suppression de la version précédente
      uses: satak/webrequest-action@master
      with:
        url: https://www.lgda.fr/ludoscore_deploiement/clean.php
        method: GET
    
    - name: Lancement du déploiement distant
      uses: satak/webrequest-action@master
      with:
        url: https://www.lgda.fr/ludoscore_deploiement/install.php
        method: GET
        
    - name: Lancement de la migration si besoin
      uses: satak/webrequest-action@master
      with:
        url: https://www.lgda.fr/ludoscoreback/finir_installation
        method: GET
      